version: '3.7'

services:
  sid_database:
    image: "postgres:13"
    container_name: sid_postgres
    environment:
      - TZ=Australia/Melbourne
    env_file: ./.env
    volumes:
      - ${REPO_PATH}/storage/pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure:5

  web:
    image: django
    build:
      context: .
      dockerfile: ./django/Dockerfile
    container_name: sid_web_container
    environment:
      - TZ=Australia/Melbourne
      - PG_HOST=${POSTGRES_HOST}
      - PG_DATABASE=${POSTGRES_DATABASE}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
    env_file: ./.env
    volumes:
      - ${REPO_PATH}:/sid/
    ports:
      - "8080:8080"
    links:
      - sid_database
    depends_on:
      - sid_database
    restart: always
